replicaCount:
  frontend: 1
  backend: 1

image:
  frontend:
    repository: xslt-playground-frontend
    tag: "latest"
    pullPolicy: IfNotPresent
  backend:
    repository: xslt-playground-backend
    tag: "latest"
    pullPolicy: IfNotPresent

service:
  frontend:
    type: ClusterIP
    port: 80
  backend:
    type: ClusterIP
    port: 8000

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: xslt.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  frontend: {}
  backend: {}

hpa:
  frontend:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  backend:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

firebase:
  enabled: true
  secretName: firebase-config
  credentialsKey: service-account.json
  configKey: firebase-config.json
  credentialsMountPath: /var/secrets/firebase

storage:
  enabled: true
  databaseUrl: postgres://postgres:postgres@db/xslt?sslmode=disable

