{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "xslt-playground.fullname" . }}-frontend
  {{- with .Values.ingress.className }}
  annotations:
    kubernetes.io/ingress.class: {{ . | quote }}
  {{- end }}
  {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
  labels:
    {{- include "xslt-playground.labels" $ | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "xslt-playground.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.service.frontend.port }}
        {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
{{- end }}

