{{- if .Values.firebase.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.firebase.secretName }}
  labels:
    {{- include "xslt-playground.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.firebase.credentialsKey }}: {{ .Values.firebase.credentials | default "" | b64enc | quote }}
  {{ .Values.firebase.configKey }}: {{ .Values.firebase.config | default "" | b64enc | quote }}
{{- end }}

