{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "xslt-playground.fullname" . }}-backend
  labels:
    {{- include "xslt-playground.labels" . | nindent 4 }}
    release: {{ .Values.metrics.serviceMonitor.releaseLabel }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "xslt-playground.selectorLabels" . | nindent 6 }}
      component: backend
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "xslt-playground.fullname" . }}-frontend
  labels:
    {{- include "xslt-playground.labels" . | nindent 4 }}
    release: {{ .Values.metrics.serviceMonitor.releaseLabel }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "xslt-playground.selectorLabels" . | nindent 6 }}
      component: frontend
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
